README.md
=> fix repo url in readme

Cargo.lock, Cargo.toml, src/admin.rs, src/config_file.rs, src/lib.rs, src/replay.rs, src/time.rs, src/worker.rs
Update rustcommon dependencies to use versions published on crates.io
=> update rustcommon dependencies

src/output/mod.rs
Change the representation of the histogram in the JSON output metrics to only contain the index and value of non-zero buckets. Since the bucket boundaries are determinstic, based on histogram parameters, these can be reconstructed rather than stored. Further, the histogram is represented in column-order rather than row-order, i.e., each field is represented in its own vector, rather than having a vector of buckets. This removes the need to repeat the field names for every bucket in the JSON output.
The combination of these changes leads to a size reduction of 4-5x in total uncompressed JSON output.
=> metrics: Reduce size of JSON output

CHANGELOG.md, Cargo.lock, Cargo.toml, src/admin/mod.rs, src/clients/http1.rs, src/clients/http2.rs, src/clients/memcache/mod.rs, src/clients/momento/mod.rs, src/clients/ping.rs, src/clients/redis/mod.rs, src/metrics/mod.rs, src/output/mod.rs, src/pubsub/momento.rs
Updates metriken to 0.2.1 and makes necessary code changes to support the new version.
=> chore: update metriken

Cargo.lock, Cargo.toml, configs/momento.toml, configs/redis.toml, src/clients/momento/commands/sorted_set_range.rs, src/clients/redis/commands/sorted_set_range.rs, src/config/workload.rs, src/workload/client.rs, src/workload/mod.rs
Adds support for zrange commands with the by_score option.
=> feat: zrange by_score

Cargo.lock
Update the Pelikan dependencies to the latest version
=> update pelikan dependencies

CHANGELOG.md, Cargo.lock, Cargo.toml
Update changelog and prepare for release v5.1.0
=> prepare for release v5.1.0

CHANGELOG.md, Cargo.lock, Cargo.toml
Update changelog and prepare for release v5.2.0
=> prepare for release v5.2.0

Cargo.lock, Cargo.toml
Prepare for next development iteration
=> prepare for next development iteration

src/main.rs
Reorders the component startup to address weird cli stats output.
By starting the CLI output before launching the workload generator and clients, we ensure that the stats in the first window cover the connect attempts on client startup.
=> fix: reorder component startup to address weird cli stats

Cargo.lock, Cargo.toml
Upgrade rdkafka dependency to fix #109
=> chore: upgrade rdkafka

configs/kafka.toml, src/config/pubsub.rs, src/pubsub/kafka.rs
This PR addresses #79, #80, and the connection timeout reporting issue when the server is not available.
=> Fix the issues in error reporting and connection timeout for Kafka client

Cargo.toml
fix duplicate entry for ringlog in cargo manifest
=> fix cargo manifest

src/main.rs
Previously, we were updating the histogram snapshots on a secondly basis. This means that the percentiles were across the "previous" second. This assumes that secondly metrics would be used and provides the highest resolution view.
However, when metrics are not collected every second, data is lost as some periods would not be reflected in the collected metrics at all.
To address this, we refresh the histogram snapshots on an interval that matches the CLI output interval. This allows the user to set an interval that makes sense for their environment.
Problem
Explain the context and why you're making that change.  What is the
problem you're trying to solve? In some cases there is not a problem
and this can be thought of being the motivation for your change.
Solution
Describe the …
=> use config interval for histogram integration period

CHANGELOG.md, Cargo.lock, Cargo.toml
Update the changelog and prepare for release 5.3.0
=> update changelog and prepare for release 5.3.0

.github/workflows/cargo.yml
Adds a simple smoketest to ci to make sure the binary works
=> ci: add memcached smoketest to ci

Cargo.lock, Cargo.toml
Resolve all cargo audit errors and warnings
=> resolve cargo audit errors and warnings

CHANGELOG.md, Cargo.lock, Cargo.toml
Update changelog and prepare for release 5.4.0
=> update changelog and prepare for release 5.4.0

CHANGELOG.md, Cargo.lock, Cargo.toml
Update changelog and prepare for release 5.5.0
=> prepare for release 5.5.0

Cargo.lock
Update the dependencies to resolve a rustsec advistory in `h2`
=> deps: update to resolve rustsec advisory

CHANGELOG.md, Cargo.lock, Cargo.toml
Update changelog and prepare for release 5.6.0
=> prepare for release 5.6.0

CHANGELOG.md, Cargo.lock, Cargo.toml
Update changelog and prepare for release 3.7.0
=> prepare for release 3.7.0

src/config/debug.rs
Removing unnecessary trait definition
=> remove unnecessary trait definition

configs/http1.toml, configs/http2.toml, configs/kafka.toml, configs/memcached.toml, configs/momento.toml, configs/momento_pubsub.toml, configs/ping.toml, configs/ratelimit.toml, configs/redis.toml, configs/smoketest-cache.toml
Updates all the example configs to have the new metrics section.
=> update the example configs

CHANGELOG.md, Cargo.lock, Cargo.toml
Update changelog and prepare for release 5.9.0
=> prepare for release 5.9.0

src/admin/mod.rs, src/main.rs, src/metrics/mod.rs
Fixes a bug in metrics exposition where some metrics may be missing on the HTTP endpoints.
Fixes #232
=> fix: missing metrics on http endpoints

CHANGELOG.md, Cargo.lock, Cargo.toml
Update changelog and prepare for release 5.9.1
=> prepare for release 5.9.1

.github/workflows/cargo.yml, Cargo.lock
Disable cargo-audit in CI due to some issues. See #248
=> disable cargo-audit in CI

CHANGELOG.md, Cargo.lock, Cargo.toml
Update changelog and prepare for release 5.10.0
=> prepare for release 5.10.0

src/output/mod.rs
The output file has a reference held by both the BufWriter
as well as the NamedTempFile, which results in both of them
attempting to close it and a fatal runtime error: "IO Safety
violation: owned file descriptor already closed".
Forget the file inside the BufWriter, so it is only closed
when the NamedTempFile is finished with it.
=> output: forget the metrics File inside the BufWriter

CHANGELOG.md, Cargo.lock, Cargo.toml
Update changelog and prepare for release 5.11.0
=> prepare for release 5.11.0

Cargo.toml
Trying to improve build times by using ThinLTO. Performance should be roughly equivalent
=> use ThinLTO

CHANGELOG.md, Cargo.lock, Cargo.toml
Update changelog and prepare for release 5.11.1
=> prepare for release 5.11.1

.github/workflows/cargo.yml
Re-enable cargo audit runs in CI
=> re-enable cargo audit in ci

CHANGELOG.md, Cargo.lock, Cargo.toml
Update changelog and prepare for release 5.12.0
=> prepare for release 5.12.0

CHANGELOG.md, Cargo.lock, Cargo.toml
Update changelog and prepare for release 5.12.1
=> prepare for release 5.12.1

src/clients/store/s3/mod.rs, src/metrics/mod.rs
Adds time-to-first-byte for s3
=> add time-to-first-byte for s3

CHANGELOG.md, Cargo.lock, Cargo.toml
Update changelog and prepare for release 5.13.0
=> prepare for release 5.13.0

CHANGELOG.md, Cargo.lock, Cargo.toml
Update changelog and prepare for release 5.14.0
=> prepare for release 5.14.0

CHANGELOG.md, Cargo.lock, Cargo.toml
Update changelog and prepare for release 5.14.1
=> prepare for release 5.14.1

configs/redis.toml, src/clients/cache/redis/commands/add.rs, src/clients/cache/redis/commands/delete.rs, src/clients/cache/redis/commands/get.rs, src/clients/cache/redis/commands/hash_delete.rs, src/clients/cache/redis/commands/hash_exists.rs, src/clients/cache/redis/commands/hash_get.rs, src/clients/cache/redis/commands/hash_get_all.rs, src/clients/cache/redis/commands/hash_increment.rs, src/clients/cache/redis/commands/hash_set.rs, src/clients/cache/redis/commands/list_fetch.rs, src/clients/cache/redis/commands/list_length.rs, src/clients/cache/redis/commands/list_pop_back.rs, src/clients/cache/redis/commands/list_pop_front.rs, src/clients/cache/redis/commands/list_push_back.rs, src/clients/cache/redis/commands/list_push_front.rs, src/clients/cache/redis/commands/ping.rs, src/clients/cache/redis/commands/replace.rs, src/clients/cache/redis/commands/set.rs, src/clients/cache/redis/commands/set_add.rs, src/clients/cache/redis/commands/set_members.rs, src/clients/cache/redis/commands/set_remove.rs, src/clients/cache/redis/commands/sorted_set_add.rs, src/clients/cache/redis/commands/sorted_set_increment.rs, src/clients/cache/redis/commands/sorted_set_range.rs, src/clients/cache/redis/commands/sorted_set_rank.rs, src/clients/cache/redis/commands/sorted_set_remove.rs, src/clients/cache/redis/commands/sorted_set_score.rs, src/clients/cache/redis/mod.rs
Adds support for connecting to redis over a unix socket.
=> add redis unix socket support

CHANGELOG.md, Cargo.lock, Cargo.toml
Update changelog and prepare for release 5.15.0
=> prepare for release 5.15.0

src/clients/store/s3/mod.rs
=> add support for s3 express

CHANGELOG.md, Cargo.lock, Cargo.toml
Update changelog and prepare for release 5.16.0
=> prepare for release 5.16.0

.github/workflows/package-rpm.yaml
Fixes for the rpm packaging workflow
=> fix rpm packaging workflow

.github/workflows/package-rpm.yaml
fix dependency package name in rpm packaging workflow
=> fix dependency package name in rpm packaging workflow

.github/workflows/package-rpm.yaml
enable devel repo when installing deps for rpm build
=> enable devel repo when installing deps for rpm build

.github/workflows/package-rpm.yaml
add git to dependencies for rpm packaging
=> add git to dependencies for rpm packaging

CHANGELOG.md, Cargo.lock, Cargo.toml
Update changelog and prepare for release 5.18.0
=> prepare for release 5.18.0

.github/workflows/cargo.yml
Fixes the ci workflows by using updating various GH actions
=> chore: fix ci workflows

src/clients/cache/momento/http.rs
We saw poor latencies when testing Momento Cache API over HTTP2. By using a minimal client outside of this repo, we were able to identify some core changes to how we handle both GETs and PUTs by moving the chunking logic into our code and relying less on the `h2` crate. 
This PR is believed to address poor PUT performance and increases the reliability of the TTFB metrics.
=> fix: momento cache h2 client high write latency

CHANGELOG.md, Cargo.lock, Cargo.toml
Update changelog and prepare for release 5.19.0
=> prepare for release 5.19.0

CHANGELOG.md, Cargo.lock, Cargo.toml
Update changelog and prepare for release 5.20.0
=> prepare for release 5.20.0

Cargo.lock, Cargo.toml, src/clients/ping/grpc/h3.rs, src/config/general.rs, src/workload/mod.rs
=> dependency updates

src/clients/pubsub/momento.rs
Problem
When trying to create a lot of momento clients at the beginning of the test to simulate subscribers in a pubsub workload, we run into dns query throttling due to the hard limit of 1000 pps that AWS imposes. 
```
Mar  7 17:37:17 localhost bash[7078]: Failed to subscribe: MomentoError { message: "The server was unavailable to handle the request; consider retrying.  If the error persists, please contact Momento.", error_code: ServerUnavailable, inner_error: Some(TonicStatus(Status { code: Unavailable, message: "error trying to connect: dns error: failed to lookup address information: Name or service not known", source: Some(tonic::transport::Error(Transport, hyper::Error(Connect, ConnectError("dns error", Custom { kind: Uncategorized, error: "failed to lookup address information: …
```
=> fix: retry subscribes on errors for duration of the test

CHANGELOG.md, Cargo.lock, Cargo.toml
Update changelog and prepare for release 5.21.0
=> prepare for release 5.21.0
