iopsystems/rpc-perf

README.md
Fixes badge and links in readme to relfect 'main' as the default branch.
=> docs: fix badge and links in readme

README.md
The workflow badge in the readme is broken due to a change in how shields.io badges work (see https://github.com/badges/shields/issues/8671). This updates the badge URL to the new, correct, URL.
=> chore: fix workflow badge in readme

Cargo.lock, Cargo.toml, src/admin.rs, src/config_file.rs
I would like to use rpc-perf for benchmarking in a script but parsing the resulting latency data out of the log messages is difficult (not to mention that you can't combine multiple runs of rpc-perf either). This PR changes rpc-perf so that it can output in both the original log format as well as a json format, with a switch in the config file to choose which one is desired. The output json also chooses to always output counts instead of rates and contains the non-zero buckets of the histogram.
=> feat: Add a json output mode for use in scripts

src/output/mod.rs
The heatmap is initialized with a total span of a minute with a resolution of 1s. This results in a total of 61 histograms, with 60 active and one empty one ready for writing. The iterator is initialized with the current histogram+2, i.e., skipping over the next empty histogram and pointing to the oldest completed one. Indexing 60 forward from there points to the current, live histogram, rather than the previous completed one.
=> fix: off-by-one error in heatmap histogram index

Cargo.lock, Cargo.toml, src/metrics/mod.rs, src/output/mod.rs
The histogram of request latencies can be reconstructed if the parameters used for minimum and maximum values and the granularity are know. Export those values along with the non-zero buckets.
=> change: output histogram parameters in the JSON

src/output/mod.rs
Fixes the output module to use the logging framework to emit the message about "no histogram" instead of using eprintln. This reduces noise when running rpc-perf with json output enabled.
=> fix: use logging framework instead of eprintln

src/clients/momento/commands/sorted_set_range.rs
Simplify the range bounds logic in the Momento client for sorted set fetch by index.
=> chore: simplify the range bounds

src/clients/momento/commands/delete.rs, src/clients/momento/commands/hash_delete.rs, src/clients/momento/commands/hash_increment.rs, src/clients/momento/commands/hash_set.rs, src/clients/momento/commands/list_fetch.rs, src/clients/momento/commands/list_length.rs, src/clients/momento/commands/list_pop_back.rs, src/clients/momento/commands/list_pop_front.rs, src/clients/momento/commands/list_push_back.rs, src/clients/momento/commands/list_push_front.rs, src/clients/momento/commands/mod.rs, src/clients/momento/commands/set.rs, src/clients/momento/commands/set_add.rs, src/clients/momento/commands/set_members.rs, src/clients/momento/commands/set_remove.rs, src/clients/momento/commands/sorted_set_add.rs, src/clients/momento/commands/sorted_set_increment.rs, src/clients/momento/commands/sorted_set_range.rs, src/clients/momento/commands/sorted_set_rank.rs, src/clients/momento/commands/sorted_set_remove.rs, src/clients/momento/commands/sorted_set_score.rs
Refactors the result handling for Momento commands by introducing
a new macro to increment the appropriate metric and transform the
result type. This reduces the duplication across commands that have
simple result handling.
=> chore: refactor result handling for Momento commands

src/main.rs, src/output/mod.rs
This PR adds a new `target_qps` field to the emitted json.
=> Add a target_qps field to the emitted rpc-perf json

src/output/mod.rs
Fixes missing (always zero) hit and miss stats in the JSON output.
=> fix: missing hit and miss stats in json output

src/config/client.rs
Increases the default buffer size for memcache client from 4KB to 16KB to accomodate larger payloads without configuration changes.
=> fix: increase default buffer size

Cargo.lock, Cargo.toml, src/output/mod.rs
The sparse histogram format used for serialization is now
available in the library so remove the local implementation
and use the library's version of the structure.
=> output: update libraries and use compact histogram 

src/net/mod.rs
Nagle's algorithm prevents transmission of small packets as long as
there are outstanding unacknowledged packets, instead buffering data
locally. When combined with delayed acknowledgements, this can lead
to poor latency with both ends of the connection waiting for each other.
Turn off Nagle's algorithm by default to improve latency.
=> feat: turn off Nagle's algorithm

CHANGELOG.md, Cargo.lock, Cargo.toml
This is a quick patch release to make the changes of #41 available. I have updated both the changelog and the version number to match.
=> Release v5.0.1

.cargo/audit.toml
A version of webpki included from the momento crate has
a potential DoS vulnerability. This is not a huge concern
since rpc-perf is not an externally facing taking unknown
production traffic. Ignore auditing for this vulnerability
for the time being to allow cargo audit to pass.
=> workflow: ignore RUSTSEC-2023-0052 during audit

.github/dependabot.yml
Change dependabot versioning strategy to lockfile-only to avoid breaking updates for 0.x versioned crates.
=> change dependabot versioning strategy

src/pubsub/kafka.rs, src/pubsub/mod.rs, src/pubsub/momento.rs
Minor refactor for pubsub regarding the message validator and trying to make the code more idiomatic.
=> minor refactor for pubsub

.github/workflows/package.yml
Update the ubuntu releases for the packaging workflow
Fixes #67
=> chore: update ubuntu releases for packaging workflow

README.md
Fix the url that the ci badge takes us to, which used the wrong branch name
=> fix ci badge url

configs/kafka.toml, src/pubsub/kafka.rs
Previously, by using a fixed group id for all kafka clients, there was no fanout of published messages. This differs from the behavior of Momento Topics and Redis PubSub.
In order to make the behavior similar to other pubsub systems, we set a unique group id per client so that each client receives all published messages.
=> kafka: use different group id for each client

Cargo.lock, lib/dataspec/Cargo.toml, lib/dataspec/src/lib.rs
I am trying to make the systemslab OpenAPI schema both valid and complete. rpcperf_dataspec does not have any schema annotations so this commit adds them.
All this is blocked behind a utoipa feature on rpcperf-dataspec so it does not get enabled by default.
=> Derive `utoipa::ToSchema` for all dataspec types

debian/control
Updates the control file to make sure that git is available during packaging
=> make sure git is available during packaging

Cargo.lock, Cargo.toml, configs/blabber.toml, configs/momento_pubsub.toml, lib/dataspec/src/lib.rs, src/clients/mod.rs, src/clients/ping.rs, src/config/client.rs, src/config/mod.rs, src/config/protocol.rs, src/config/pubsub.rs, src/output/mod.rs, src/pubsub/blabber.rs, src/pubsub/mod.rs
Adds support for the `blabber` protocol in which the server will periodically publish messages to subscribers.
This is implemented as a pubsub protocol.
Adds latency distribution information to the dataspec for pubsub.
=> add blabber protocol support

configs/blabber.toml, configs/http1.toml, configs/http2.toml, configs/kafka.toml, configs/memcached.toml, configs/momento.toml, configs/momento_pubsub.toml, configs/ping.toml, configs/ratelimit.toml, configs/redis.toml, configs/segcache.toml, src/admin/mod.rs, src/config/workload.rs, src/main.rs, src/workload/mod.rs
The configuration currently allows rpc-perf to be setup with a single static
ratelimit for the entire run and exposes an endpoint through which this can
be controlled externally. This adds a basic workload definition for dynamic
ratelimiting in the configuration, as well as a background thread that modifies
the ratelimit using the endpoint so that rpc-perf can run with a dynamic
ratelimit without relying on an external controller.
=> feat: add internal ratelimit controller

configs/ratelimit.toml, src/config/mod.rs, src/config/workload.rs, src/main.rs, src/workload/mod.rs
Allow the internal ratelimit controller to explore desired ratelimits
in random order as well as mirroring the ramp-up or looping around
and running the test again after a ramp-up cycle.
=> feat: add looping, mirroring, and randomization to ratelimit controller

Cargo.lock
As it turns out metriken v5 is not compatible with metriken v0.3.3 and metriken v0.4.0. Newer updated versions of metriken fix this so we can just update to bypass the error.
This may be worth fixing upstream in metriken-core? It shouldn't be a problem for existing consumers if they use the latest version so idk.
I have now included the verison bump to v0.3.5 instead of v0.3.4 due to the stack overflow issue with metriken v0.3.4.
=> Update metriken v0.3.3 to v0.3.5

src/clients/momento/commands/list_length.rs
Problem
When using a workload config like below, no `list_length` calls were making it to momento and the number of `list_fetch` calls was higher than expected.
```
[[workload.keyspace]]
weight = 180
klen = 20
nkeys = 100
inner_keys_klen = 4
inner_keys_nkeys = 1_000
commands = [
{ verb = "list_fetch", weight = 210 },
{ verb = "list_length", weight = 210 },
{ verb = "list_push_back", weight = 1, cardinality = 5, truncate = 10 },
]
```
Solution
Made the `list_length` verb call the correct momento api.
=> fix: route list_length verb correctly for momento

src/admin/mod.rs, src/main.rs, src/metrics/mod.rs, src/output/mod.rs, src/workload/mod.rs
The ratelimit is currently extracted from the ratelimiter every time
during output. Export it as a metrics gauge instead.
=> metrics: export ratelimit as a gauge

src/output/mod.rs
The stats output now uses the snapshot mechanism from metriken-exposition.
Remove the superfluous (and unused) instance of MetricsSnapshot.
=> output: remove unnecessary MetricsSnapshot instance

Cargo.lock
Update mio due to RUSTSEC-2024-0019.
=> chore(deps): bump mio from 0.8.10 to 0.8.11

src/output/mod.rs
The summary percentiles produced by the parquet file currently
are summaries of free-running histograms and give one summary
percentiles at any instant, since the beginning of time. This
isn't very useful, and confusing, so instead just don't track
summary percentiles.
=> output: remove summary percentiles from parquet file

.github/workflows/package.yml
Cross-compiling to arm64 fails due to some errors while linking
boring-ssl, which also ends up preventing the x86 packages from being
built and uploaded. Disable cross-compiling for now. Also remove
unsupported Ubuntu versions.
=> packaging: remove arm64 cross-compilation

src/main.rs, src/output/mod.rs
Aligns log output and metrics output to the top of the second. This allows for a simple alignment strategy when working with data from multiple sources.
=> align reporting to the top of the second

.github/workflows/cargo.yml, Cargo.lock, Cargo.toml, src/net/mod.rs
We experienced linking issues when adding TLS support for the kafka client. This was because we depend on boringssl which has symbol collisions with openssl during linking. 
This change gives us the ability to build with either openssl or boringssl as the TLS/SSL provider. The default is switched to openssl so we can integrate the kafka TLS support.
=> switch to openssl

.github/workflows/cargo.yml, Cargo.lock, Cargo.toml, configs/blabber.toml, configs/kafka.toml, configs/memcached.toml, configs/momento.toml, configs/momento_pubsub.toml, configs/redis.toml, configs/segcache.toml, configs/smoketest.toml, src/config/workload.rs, src/workload/mod.rs
Adds approximate compression ratio targeting for messages and values.
This is done by limiting the number of random bytes in the payload to the first N bytes and iteratively estimating the compression ratio using gzip.
=> feat: add approximate compression ratio for messages and values

Cargo.lock, src/metrics/mod.rs, src/workload/mod.rs
Adds two new metrics to track when the ratelimiter bucket overflows and when the work queue is full. These metrics allow us to see when the workload generation is falling behind or when the client/server are falling behind.
=> add metrics for dropped requests

src/admin/mod.rs, src/output/mod.rs
Adds a /quitquitquit endpoint so that the test can be terminated early.
=> add /quitquitquit

configs/segcache.toml, src/config/general.rs, src/config/metrics.rs, src/config/mod.rs, src/output/mod.rs
Move configuration of metrics output to a separate section
in the configuration file. At the moment, allow metrics
configuration to be specified in the old, i.e, via the
general section, or the new, i.e., via the metrics section.
If configuration parameters in both sections are in conflict,
use the ones from the metrics section.
=> config: move metrics configuration to separate section

Cargo.lock, Cargo.toml, src/clients/http1.rs, src/clients/http2.rs, src/clients/memcache/mod.rs, src/clients/mod.rs, src/clients/momento/mod.rs, src/clients/ping.rs, src/clients/redis/mod.rs, src/config/mod.rs, src/config/storage.rs, src/config/workload.rs, src/main.rs, src/metrics/mod.rs, src/output/mod.rs, src/store/mod.rs, src/store/momento.rs, src/workload/client.rs, src/workload/mod.rs, src/workload/store.rs
Problem
* Momento client needs to be updated to `v0.42.0`
* Need support for Momento `store` workflow
* Unlike Redis/Memcache/Momento cache, a `store` is a high-performance, low-latency storage system for storing persistent items
* Unlike Redis/Memcache/Momento cache, the amount of APIs a Momento `store` supports is very small for now: get/set/delete
* Need support to have a `storage` workflow run simultaneously to a `cache` workflow
Solution
* Upgraded Momento client
* Added support for a separate `storage` client config. `client` and `storage` should not share the same config settings
* Added support for separate `store` workflow(s), only supporting the Momento protocol (for now).
* DRY'd up the `WorkItem` typing so that reconnection code can be reused between the `cache` client and …
=> momento: support store workflow

.github/workflows/package.yml
Fixes the packaging workflow by dropping old debian and ubuntu versions, updating actions, etc.
Will now publish artifacts to the release.
=> fix packaging workflow

.github/workflows/cargo.yml
Updates the CI config to use macos-latest for the runner image
=> use macos-latest for github macos runner image

src/clients/cache/redis/commands/set.rs
I was getting `syntax error` when running load test against Redis with SET commands.
There was a bug where we used an incorrect SET syntax.
=> fix redis SET command

src/main.rs
Fixes runtime panic when doing momento-http load test due to
missing default rustls provider.
=> fix: set default rustls provider

src/clients/cache/momento/http.rs
Fix to read the complete Momento HTTP response before considering the response as completed.
=> fix: read complete Momento HTTP response

src/clients/cache/momento/http.rs
Fixes the handling of large http payloads with the Momento HTTP API by making sure we release capacity back to the connection and stream when each chunk is read.
Adds the ability to log TLS keys to a key log file for easier troubleshooting with packet captures.
=> fix for momento http with large payloads

src/main.rs, src/workload/mod.rs
To avoid an intial burst of requests when load level is increased the work queues have had their capacity reduced and the ratelimiter max tokens is set to the batch size.
=> avoid request burst on ratelimit changes

Cargo.lock, Cargo.toml
Before this commit, building on Momento build machines would cause a build error due to "pairs" is not exported by the List::Util module.
See upstream issue here: https://github.com/openssl/openssl/issues/25366
=> pin openssl-src to 300.3.1+3.3.1 to allow builds on older machines

Cargo.toml
Addresses a cargo warning about semver metadata for openssl-src
=> remove semver metadata for openssl-src

src/clients/cache/momento/http.rs
Previously we would get InvalidDnsNameError error if we specified the port number for momento_http, e.g.
endpoints = ["https://api.cache.developer-vir-dev.preprod.a.momentohq.com:9003"]
=> allow port number to be specified for momento_http protocol

.github/workflows/cargo.yml, configs/smoketest-oltp.toml, src/clients/cache/mod.rs, src/clients/cache/momento/commands/hash_set.rs, src/clients/oltp/mod.rs, src/clients/store/s3/mod.rs, src/workload/client.rs, src/workload/mod.rs, src/workload/store.rs
Improves the speed of value generation by preallocating a buffer of random bytes and avoiding allocations. This is particularly noticeable when value sizes are large.
Fixes some bugs with client initialization which cause problems for OLTP workload.
=> improve speed of value generation

.github/workflows/package.yml
The packaging workflow is missing a required build dependency on libssl-dev
=> packaging: missing libssl-dev

src/clients/cache/momento/http.rs
TTL is not optional for Momento HTTP Set requests. This change enforces this requirement and uses a 15 minute default TTL if it has not been configured in the workload config.
Fixes #298
=> default ttl for momento http set requests

src/clients/cache/momento/http.rs
Removes the error log message when the channel is closed. This can occur at the end of a run and is not a true error.
=> remove error log message when channel is closed

src/clients/store/s3/mod.rs
Tunes the S3 client receive buffer
=> increase s3 client http1 buffer size

src/main.rs, src/workload/mod.rs
The current settings for work queue depth and token bucket capacity are not sufficient for generating high-throughput traffic in some situations. This change increases the queue depth and token bucket capacity multipliers and moves them into since consts in each relevant module.
=> increases the work queue depth and token bucket capacity

Cargo.toml
Adds metadata section for rpm generation to the Cargo manifest.
=> add metadata for rpm generation

src/main.rs, src/workload/mod.rs
Adds some debug level log messages during startup to make it easier to see what phase of startup is taking a long time.
Avoids the value buffer shuffle when non-compressible values have been used.
=> debugging startup times

src/clients/pubsub/momento.rs, src/config/workload.rs, src/workload/mod.rs
Problem
A momento client can only support a maximum of 100 subscriptions due to the server side GRPC restriction on concurrent streams per connection. The current implementation assumes that all subscribers subscribe to all topics.
We are hence unable to test workflows like 10 topics with 100 subscribers each and we also run into issues if the number of subscriptions created is more than 100 * number of clients.
Solution
Add a configuration option for subscribers per topic and add runtime checks to fail if the configuration tries to create more subscriptions than what the clients can support.
=> feat: configure subscribers_per_topic for momento pubsub workflow

src/main.rs, src/output/mod.rs
Problem
1. The http endpoint to scrape metrics from was not available when running in replay mode.
2. Log output was empty in replay mode
3. rpc-perf panics if replay config is entirely missing but replay subcommand is provided
Solution
I made targeted fixes for each issue in this PR but I think an overall refactor of the replay mode config is needed. I would like to see the replay config merged into the `workload` config section and have it choose between the command log input or generate values randomly. I don't have the bandwidth for that right now though.
=> fix: replay mode fixes for metrics, log and config validation
